plugins: 
  - serverless-webpack
  - serverless-offline

custom.webpack:
  webpackIncludeModules: true

service: serverless-webpack-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
    - ${file(./src/functions.yml)}
