plugins: 
  - serverless-webpack
  - serverless-plugin-typescript
  - serverless-offline
  

service: serverless-graphql-bootstrap

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
    - ${file(./src/functions.yml)}
