plugins: 
  - serverless-webpack
  - serverless-offline

custom.webpack:
  webpackIncludeModules: true
  
custom.dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    # seed:
    #   test:
    #     sources:
    #       - table: Users
    #         sources: [seed-data/Users.json]
    #       - table: Tweets
    #         sources: [seed-data/Tweets.json]

service: serverless-typescript-graphql

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
    - ${file(./src/functions.yml)}
