plugins: 
  - serverless-webpack
  - serverless-offline

service: serverless-typescript-graphql

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
    - ${file(./src/functions.yml)}
